### ISSUE TITLE
Cannot read property '2'

### ISSUE THREAD

**Issue by wwarlock** [RomanMinkin/gulp-javascriptobfuscator#2]
Just after install and run
```javascript
events.js:165
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property '2' of null
    at IncomingMessage.<anonymous> ($__projectROOT__/node_modules/gulp-javascriptobfuscator/index.js:97:73)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
Emitted 'error' event at:
    at DestroyableTransform.onerror ($__projectROOT__/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at DestroyableTransform.emit (events.js:180:13)
    at onwriteError ($__projectROOT__/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:439:12)
    at onwrite ($__projectROOT__/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:460:11)
    at WritableState.onwrite ($__projectROOT__/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:180:5)
    at DestroyableTransform.afterTransform ($__projectROOT__/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:93:3)
    at $__projectROOT__/node_modules/gulp-javascriptobfuscator/index.js:129:18
    at IncomingMessage.<anonymous> ($__projectROOT__/node_modules/gulp-javascriptobfuscator/index.js:100:47)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
```
And no one obfuscated `*.js`-file

**Comment by RomanMinkin** [comment]
@wwarlock I'm actually not the original creator of this library. Original one lives only in `npm` and there is no source code available https://www.npmjs.com/package/gulp-javascriptobfuscator

I just created this repo so it would not be missed, but i could not reach the original author.

So even if i fix this cod, I still can't publish the changes to `npm`.

**Comment by RomanMinkin** [comment]
@wwarlock Just sent another request to the original author.

**Comment by wwarlock** [comment]
Wow, thanks to you in any case.

**Comment by wwarlock** [comment]
I wrote him too

**Comment by wwarlock** [comment]
And the author's answer is
> This package is not maintaining any more due I use minify & uglify  library to obfuscate java script code. I've just receiving email from other developer who want to maintaining this library so I give you his respo and add him as publisher.
> 
> https://github.com/RomanMinkin/gulp-javascriptobfuscator
> 
> Best Regards,
> Phuong Tang Khai,

**Comment by RomanMinkin** [comment]
@wwarlock Yes i got the reply too and Phuong gave me rights to publish to npm. I will star from here.

**Comment by RomanMinkin** [comment]
@wwarlock can you pull and try #3 , if fix i'll merge and publish

**Comment by RomanMinkin** [comment]
@wwarlock merged to `master`

**Comment by wwarlock** [comment]
Thanks, I'll try this soon
